import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['introduction/intro'],
    },
    {
      type: 'category',
      label: 'ROS 2',
      items: ['ros2/ros2-basics', 'ros2/ros2-advanced'],
    },
    {
      type: 'category',
      label: 'Digital Twin',
      items: ['digital-twin/physics-simulation', 'digital-twin/sensor-integration'],
    },
    {
      type: 'category',
      label: 'NVIDIA Isaac',
      items: ['isaac/perception-vslam', 'isaac/navigation-sim-to-real'],
    },
    {
      type: 'category',
      label: 'VLA',
      items: ['vla/voice-to-action', 'vla/llm-cognitive-planning', 'vla/conversational-robotics'],
    },
    {
      type: 'category',
      label: 'Capstone',
      items: ['capstone/end-to-end-project'],
    },
    {
      type: 'category',
      label: 'Conclusion',
      items: ['conclusion/summary-future-trends'],
    },
  ],
};

export default sidebars;
